# Generated by Django 4.2.5 on 2023-09-27 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('path', models.CharField(max_length=1000)),
                ('failed_executions', models.IntegerField()),
                ('successfull_executions', models.IntegerField()),
                ('total_executions', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5000)),
                ('success', models.BooleanField()),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.automation')),
            ],
        ),
    ]
