# Generated by Django 4.2.5 on 2023-09-27 02:16

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_automation_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='schedule_param',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[api.validators.validate_cron]),
        ),
    ]
