# Generated by Django 4.2.5 on 2023-09-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='failed_executions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='automation',
            name='successfull_executions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='automation',
            name='total_executions',
            field=models.IntegerField(default=0),
        ),
    ]
